name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: csunibo/config/.github/workflows/statik.yml@main
    with:
      regex_include: "\\.(pdf|link|txt|apkg)$"
